In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
os.getcwd()

'C:\\Users\\pmgho'

In [3]:
os.chdir('C:\\Users\\pmgho\\Downloads\\Prajwal Machine Learning Data Set\\')

In [4]:
os.getcwd()

'C:\\Users\\pmgho\\Downloads\\Prajwal Machine Learning Data Set'

In [5]:
df=pd.read_csv('Customer Purchase.csv')
df

Customer ID  Age  Gender Education   Review Purchased
0          1021   30  Female    School  Average        No
1          1022   68  Female        UG     Poor        No
2          1023   70  Female        PG     Good        No
3          1024   72  Female        PG     Good        No
4          1025   16  Female        UG  Average        No
5          1026   31  Female    School  Average       Yes
6          1027   18    Male    School     Good        No
7          1028   60  Female    School     Poor       Yes
8          1029   65  Female        UG  Average        No
9          1030   74    Male        UG     Good       Yes
10         1031   98  Female        UG     Good       Yes
11         1032   74    Male        UG     Good       Yes
12         1033   51    Male    School     Poor        No
13         1034   57  Female    School  Average        No
14         1035   15    Male        PG     Poor       Yes
15         1036   75    Male        UG     Poor        No
16         1037   59    Male        UG     Poor       Yes
17         1038   22  Female        UG     Poor       Yes
18         1039   19    Male    School     Good        No
19         1040   97    Male        PG     Poor       Yes
20         1041   57  Female    School  Average       Yes
21         1042   32    Male        PG  Average        No
22         1043   18  Female        PG     Poor       Yes
23         1044   96  Female    School     Good        No
24         1045   16  Female        PG  Average       Yes
25         1046   57  Female    School     Good        No
26         1047   53  Female        PG     Poor        No
27         1048   69  Female        PG     Poor        No
28         1049   48    Male    School     Poor        No
29         1050   83  Female        UG  Average       Yes
30         1051   73    Male        UG  Average        No
31         1052   22  Female    School     Poor       Yes
32         1053   92    Male        UG  Average       Yes
33         1054   89  Female        PG     Good       Yes
34         1055   86    Male    School  Average        No
35         1056   74    Male    School     Poor       Yes
36         1057   34  Female        UG     Good       Yes
37         1058   94    Male        PG  Average       Yes
38         1059   45  Female    School     Good        No
39         1060   76    Male        PG     Poor        No
40         1061   39    Male    School     Good        No
41         1062   23    Male        PG     Good       Yes
42         1063   30  Female        PG     Good       Yes
43         1064   27    Male        PG     Poor        No
44         1065   77  Female        UG  Average        No
45         1066   61    Male        PG     Poor       Yes
46         1067   64  Female        PG     Poor        No
47         1068   38  Female        PG     Good       Yes
48         1069   39  Female        UG     Good       Yes
49         1070   25  Female        UG     Good        No

In [6]:
df.head()

Customer ID  Age  Gender Education   Review Purchased
0         1021   30  Female    School  Average        No
1         1022   68  Female        UG     Poor        No
2         1023   70  Female        PG     Good        No
3         1024   72  Female        PG     Good        No
4         1025   16  Female        UG  Average        No

In [7]:
df.drop('Customer ID',axis='columns',inplace=True)

In [8]:
df

Age  Gender Education   Review Purchased
0    30  Female    School  Average        No
1    68  Female        UG     Poor        No
2    70  Female        PG     Good        No
3    72  Female        PG     Good        No
4    16  Female        UG  Average        No
5    31  Female    School  Average       Yes
6    18    Male    School     Good        No
7    60  Female    School     Poor       Yes
8    65  Female        UG  Average        No
9    74    Male        UG     Good       Yes
10   98  Female        UG     Good       Yes
11   74    Male        UG     Good       Yes
12   51    Male    School     Poor        No
13   57  Female    School  Average        No
14   15    Male        PG     Poor       Yes
15   75    Male        UG     Poor        No
16   59    Male        UG     Poor       Yes
17   22  Female        UG     Poor       Yes
18   19    Male    School     Good        No
19   97    Male        PG     Poor       Yes
20   57  Female    School  Average       Yes
21   32    Male        PG  Average        No
22   18  Female        PG     Poor       Yes
23   96  Female    School     Good        No
24   16  Female        PG  Average       Yes
25   57  Female    School     Good        No
26   53  Female        PG     Poor        No
27   69  Female        PG     Poor        No
28   48    Male    School     Poor        No
29   83  Female        UG  Average       Yes
30   73    Male        UG  Average        No
31   22  Female    School     Poor       Yes
32   92    Male        UG  Average       Yes
33   89  Female        PG     Good       Yes
34   86    Male    School  Average        No
35   74    Male    School     Poor       Yes
36   34  Female        UG     Good       Yes
37   94    Male        PG  Average       Yes
38   45  Female    School     Good        No
39   76    Male        PG     Poor        No
40   39    Male    School     Good        No
41   23    Male        PG     Good       Yes
42   30  Female        PG     Good       Yes
43   27    Male        PG     Poor        No
44   77  Female        UG  Average        No
45   61    Male        PG     Poor       Yes
46   64  Female        PG     Poor        No
47   38  Female        PG     Good       Yes
48   39  Female        UG     Good       Yes
49   25  Female        UG     Good        No

In [9]:
df.head()

Age  Gender Education   Review Purchased
0   30  Female    School  Average        No
1   68  Female        UG     Poor        No
2   70  Female        PG     Good        No
3   72  Female        PG     Good        No
4   16  Female        UG  Average        No

In [10]:
df=df.iloc[:,2:]
df

Education   Review Purchased
0     School  Average        No
1         UG     Poor        No
2         PG     Good        No
3         PG     Good        No
4         UG  Average        No
5     School  Average       Yes
6     School     Good        No
7     School     Poor       Yes
8         UG  Average        No
9         UG     Good       Yes
10        UG     Good       Yes
11        UG     Good       Yes
12    School     Poor        No
13    School  Average        No
14        PG     Poor       Yes
15        UG     Poor        No
16        UG     Poor       Yes
17        UG     Poor       Yes
18    School     Good        No
19        PG     Poor       Yes
20    School  Average       Yes
21        PG  Average        No
22        PG     Poor       Yes
23    School     Good        No
24        PG  Average       Yes
25    School     Good        No
26        PG     Poor        No
27        PG     Poor        No
28    School     Poor        No
29        UG  Average       Yes
30        UG  Average        No
31    School     Poor       Yes
32        UG  Average       Yes
33        PG     Good       Yes
34    School  Average        No
35    School     Poor       Yes
36        UG     Good       Yes
37        PG  Average       Yes
38    School     Good        No
39        PG     Poor        No
40    School     Good        No
41        PG     Good       Yes
42        PG     Good       Yes
43        PG     Poor        No
44        UG  Average        No
45        PG     Poor       Yes
46        PG     Poor        No
47        PG     Good       Yes
48        UG     Good       Yes
49        UG     Good        No

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [12]:
X_train

Education   Review
49        UG     Good
34    School  Average
24        PG  Average
21        PG  Average
23    School     Good
30        UG  Average
41        PG     Good
13    School  Average
33        PG     Good
46        PG     Poor
10        UG     Good
26        PG     Poor
45        PG     Poor
39        PG     Poor
29        UG  Average
40    School     Good
18    School     Good
37        PG  Average
0     School  Average
15        UG     Poor
36        UG     Good
4         UG  Average
12    School     Poor
47        PG     Good
17        UG     Poor
3         PG     Good
22        PG     Poor
28    School     Poor
25    School     Good
16        UG     Poor
32        UG  Average
14        PG     Poor
1         UG     Poor
42        PG     Good
19        PG     Poor
20    School  Average
7     School     Poor
35    School     Poor
2         PG     Good
38    School     Good

In [15]:
from sklearn.preprocessing import OrdinalEncoder 

In [17]:
oe=OrdinalEncoder(categories=[['School','UG','PG'],['Poor','Average','Good']])
oe

OrdinalEncoder(categories=[['School', 'UG', 'PG'], ['Poor', 'Average', 'Good']])

In [18]:
oe.fit(X_train)

OrdinalEncoder(categories=[['School', 'UG', 'PG'], ['Poor', 'Average', 'Good']])

In [19]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [20]:
X_train

array([[1., 2.],
       [0., 1.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [1., 0.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.]])

In [21]:
X_test

array([[1., 1.],
       [1., 1.],
       [1., 2.],
       [0., 2.],
       [1., 2.],
       [0., 1.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [1., 2.]])

In [22]:
oe.categories_

[array(['School', 'UG', 'PG'], dtype=object),
 array(['Poor', 'Average', 'Good'], dtype=object)]

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
le=LabelEncoder()

In [27]:
le.fit(y_train)

LabelEncoder()

In [29]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [30]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [31]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0])

In [32]:
y_test

array([0, 0, 1, 0, 1, 1, 0, 0, 1, 1])